---
title: "Promotions and Exits"
author: "Tate Huffman"
date: "2/1/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
library(tidyverse)
bat_performance = read_csv('../Data/Clean/bat/bat_performance_min_40pa.csv')
pitch_performance = read_csv('../Data/Clean/pitch/pitch_performance_min_20bf.csv')

n_years <- 10 # maximum number of years for a player in the data
```

## Overview

This is part of a series of RMarkdown files that will break down the code contained in the document at the end of the fall. This file in particular will combine the recalculated information for promotions and exits into one dataframe in order to more accurately calculate a true application of the O'Flaherty and Siow model.

## TEXT HERE

TEXT HERE

```{r exits}

# Batter exits

n_bat <- bat_performance %>% # number of unique batters meeting the PA threshold
  select(Name) %>% 
  pull() %>% 
  unique() %>% 
  length()

exit_distr_bat <- bat_performance %>% 
  group_by(Name) %>% 
  summarise(n_year = n_distinct(Year),
            ever_exit = if_else(max(exit) == 1, 1, 0)) %>% 
  group_by(ever_exit, n_year) %>% 
  summarise(n_players = n_distinct(Name)) %>% 
  ungroup() %>% 
  add_row(ever_exit = 0,
          n_year = 10,
          n_players = sum(pull(select(filter(., ever_exit == 0), n_players)))) %>% 
  slice(11:21) %>% 
  mutate(pct = n_players / n_bat,
         pos = 'Batters')


exit_distr_bat <- bat_performance %>% # distribution of player exit times
  group_by(Name) %>%
  summarise(n_year = n_distinct(Year)) %>% 
  group_by(n_year) %>% 
  summarise(n_players = n_distinct(Name)) %>% 
  filter(n_year <= n_years) %>% 
  mutate(pct = n_players / n_bat,
         pos = 'Batters') # 100x multiplier to make it a true percent

# Pitcher exits

n_pitch <- pitch_performance %>% # number of unique pitchers
  select(Name) %>% 
  pull() %>% 
  unique() %>% 
  length()

exit_distr_pitch <- pitch_performance %>% # distribution of player exit times
  group_by(Name) %>%
  summarise(n_year = n_distinct(Year)) %>% 
  group_by(n_year) %>% 
  summarise(n_players = n_distinct(Name)) %>% 
  filter(n_year <= n_years) %>% 
  mutate(pct = n_players / n_pitch,
         pos = 'Pitchers') # 100x multiplier to make it a true percent

# Merging the batter and pitcher dataframes

n_total <- n_bat + n_pitch

exit_distr <- exit_distr_bat %>% 
  bind_cols(exit_distr_pitch) %>% 
  mutate(n_year = n_year...1,
         n_players = n_players...2 + n_players...6,
         pct = n_players / n_total) %>% 
  select(n_year, n_players, pct)

```

